import { db } from '../../db/database.js'
import { applyThemeToDocument } from '../themes/themes.js'
function makeId(prefix){return `${prefix}-${crypto.randomUUID()}`}
export async function createBookDraft(title='',themeId=null){const now=new Date().toISOString();const book={id:makeId('book'),title:title.trim(),subtitle:'',themeId,status:'draft',pageIds:[],photoIds:[],createdAt:now,updatedAt:now,deletedAt:null,backupStatus:'device-only',schemaVersion:1};await db.books.add(book);if(themeId)applyThemeToDocument(themeId);return book}
export async function updateBookTheme(bookId,themeId){await db.books.update(bookId,{themeId,updatedAt:new Date().toISOString()});applyThemeToDocument(themeId);return db.books.get(bookId)}
export async function updateBookTitle(bookId,title){await db.books.update(bookId,{title:title.trim(),updatedAt:new Date().toISOString()});return db.books.get(bookId)}
async function fileChecksum(file){if(!crypto.subtle)return `${file.name}-${file.size}-${file.lastModified}`;const buffer=await file.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function makeThumbnailBlob(file){if(!('createImageBitmap'in window))return file;const bitmap=await createImageBitmap(file),maxEdge=720,scale=Math.min(1,maxEdge/Math.max(bitmap.width,bitmap.height)),width=Math.max(1,Math.round(bitmap.width*scale)),height=Math.max(1,Math.round(bitmap.height*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{alpha:false});context.drawImage(bitmap,0,0,width,height);bitmap.close();return new Promise((resolve,reject)=>{canvas.toBlob(blob=>(blob?resolve(blob):reject(new Error('Could not create thumbnail'))),'image/jpeg',.82)})}
export async function importPhotos(bookId,fileList,onProgress){const files=[...fileList].filter(file=>file.type.startsWith('image/')),importedIds=[];for(let index=0;index<files.length;index+=1){const file=files[index],photoId=makeId('photo'),thumbnailId=makeId('thumb'),createdAt=new Date().toISOString(),checksum=await fileChecksum(file),thumbnailBlob=await makeThumbnailBlob(file);await db.transaction('rw',db.photos,db.thumbnails,db.books,async()=>{await db.photos.add({id:photoId,bookId,blob:file,filename:file.name,mimeType:file.type,size:file.size,checksum,createdAt});await db.thumbnails.add({id:thumbnailId,photoId,blob:thumbnailBlob});const book=await db.books.get(bookId),nextPhotoIds=[...(book?.photoIds??[]),photoId];await db.books.update(bookId,{photoIds:nextPhotoIds,updatedAt:createdAt})});importedIds.push(photoId);onProgress?.({completed:index+1,total:files.length})}return importedIds}
export async function listBooks(){const books=await db.books.toArray();return books.filter(book=>!book.deletedAt&&book.title?.trim()).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))}
