import { useEffect, useRef, useState } from 'react'
import { exportPortableBackup, downloadBackup, getBackupStatus, inspectPortableBackup, restorePortableBackup } from './backupService.js'
import CloudAccountControl from '../cloud/CloudAccountControl.jsx'

function formatDate(value) { if (!value) return 'Never'; try { return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) } catch { return value } }

export default function BackupDock() {
  const inputRef=useRef(null); const [open,setOpen]=useState(false); const [status,setStatus]=useState(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [pendingRestore,setPendingRestore]=useState(null); const [pendingManifest,setPendingManifest]=useState(null)
  async function refreshStatus(){setStatus(await getBackupStatus())}
  useEffect(()=>{refreshStatus()},[])
  async function handleExport(){setBusy(true);setMessage('');try{const result=await exportPortableBackup();downloadBackup(result.blob,result.filename);setMessage(`Backup created: ${result.manifest.counts.books} books and ${result.manifest.counts.photos} photos.`);await refreshStatus()}catch(error){console.error(error);setMessage('Backup could not be created. Nothing in Little Stories was changed.')}finally{setBusy(false)}}
  async function chooseRestore(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setMessage('');try{const manifest=await inspectPortableBackup(file);setPendingRestore(file);setPendingManifest(manifest)}catch(error){setMessage(error.message||'That backup could not be read.')}finally{setBusy(false)}}
  async function confirmRestore(){if(!pendingRestore)return;setBusy(true);try{const result=await restorePortableBackup(pendingRestore);setMessage(`Restore complete: ${result.bookCount} books and ${result.photoCount} photos restored.`);setTimeout(()=>location.reload(),700)}catch(error){setMessage(error.message||'Restore failed.');setBusy(false)}}
  return <><button className="backup-fab" type="button" onClick={()=>setOpen(true)} aria-label="Backup and recovery">☁</button>{open&&<div className="backup-modal-backdrop" onClick={()=>!busy&&setOpen(false)}><section className="backup-modal" onClick={(e)=>e.stopPropagation()}><div className="backup-modal-heading"><div><p className="backup-kicker">Data Safety</p><h2>Backup & Recovery</h2></div><button className="backup-close" onClick={()=>setOpen(false)}>×</button></div><div className="cloud-backup-section"><p className="backup-kicker">Automatic Off-Device Backup</p><h3>Little Stories Cloud</h3><p className="backup-copy">Your private online recovery copy belongs to your Little Stories account. Teachers do not need to connect Google Drive or another personal storage service.</p><CloudAccountControl/></div><div className="backup-status-card"><strong>Portable backup</strong><span>Last exported: {formatDate(status?.lastBackedUpAt)}</span></div><p className="backup-copy">You can still keep your own downloadable recovery file as an extra safety copy.</p><button className="backup-primary" onClick={handleExport} disabled={busy}>{busy?'Working…':'Export Complete Backup'}</button><button className="backup-secondary" onClick={()=>inputRef.current?.click()} disabled={busy}>Restore From Backup File</button><input ref={inputRef} className="backup-file-input" type="file" accept=".zip,.littlestories" onChange={chooseRestore}/>{message&&<div className="backup-message">{message}</div>}</section></div>}{pendingRestore&&pendingManifest&&<div className="backup-modal-backdrop"><section className="backup-modal confirm-restore"><p className="backup-kicker">Ready to Restore</p><h2>Replace local data?</h2><p className="backup-copy">This backup contains <strong>{pendingManifest.counts.books} books</strong> and <strong>{pendingManifest.counts.photos} photos</strong>.</p><div className="backup-warning"><strong>This replaces the Little Stories data on this device.</strong> The archive is validated before replacement.</div><button className="backup-danger" onClick={confirmRestore} disabled={busy}>{busy?'Restoring…':'Yes, Restore This Backup'}</button><button className="backup-secondary" onClick={()=>{setPendingRestore(null);setPendingManifest(null)}}>Cancel</button></section></div>}</>
}
